USE [master]
GO

/****** Object:  Database [NEWS_WEBSITE]    Script Date: 7/3/2021 1:17:17 AM ******/
CREATE DATABASE [NEWS_WEBSITE]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'NEWS_WEBSITE', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\NEWS_WEBSITE.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'NEWS_WEBSITE_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\NEWS_WEBSITE_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [NEWS_WEBSITE].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [NEWS_WEBSITE] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [NEWS_WEBSITE] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [NEWS_WEBSITE] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [NEWS_WEBSITE] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [NEWS_WEBSITE] SET ARITHABORT OFF 
GO

ALTER DATABASE [NEWS_WEBSITE] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [NEWS_WEBSITE] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [NEWS_WEBSITE] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [NEWS_WEBSITE] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [NEWS_WEBSITE] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [NEWS_WEBSITE] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [NEWS_WEBSITE] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [NEWS_WEBSITE] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [NEWS_WEBSITE] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [NEWS_WEBSITE] SET  DISABLE_BROKER 
GO

ALTER DATABASE [NEWS_WEBSITE] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [NEWS_WEBSITE] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [NEWS_WEBSITE] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [NEWS_WEBSITE] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [NEWS_WEBSITE] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [NEWS_WEBSITE] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [NEWS_WEBSITE] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [NEWS_WEBSITE] SET RECOVERY FULL 
GO

ALTER DATABASE [NEWS_WEBSITE] SET  MULTI_USER 
GO

ALTER DATABASE [NEWS_WEBSITE] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [NEWS_WEBSITE] SET DB_CHAINING OFF 
GO

ALTER DATABASE [NEWS_WEBSITE] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [NEWS_WEBSITE] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [NEWS_WEBSITE] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [NEWS_WEBSITE] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [NEWS_WEBSITE] SET QUERY_STORE = OFF
GO

ALTER DATABASE [NEWS_WEBSITE] SET  READ_WRITE 
GO

USE [NEWS_WEBSITE]
GO

CREATE TABLE tblUSER (
UserID int PRIMARY KEY,
PromoID int,
CONSTRAINT FK_UserPromoted FOREIGN KEY (PromoID)
REFERENCES tblUSER(UserID),
UserName nvarchar(50) NOT NULL,
UserMail nvarchar(50) NOT NULL,
UserPass nvarchar(30) NOT NULL,
DisplayName nvarchar(50),
RegisterDate date NOT NULL,
UserRole int NOT NULL
)
GO

CREATE TABLE tblMEDIA (
MedID int PRIMARY KEY,
Author int NOT NULL DEFAULT 1,
CONSTRAINT FK_UserUpload FOREIGN KEY (Author)
REFERENCES tblUSER(UserID) ON DELETE SET DEFAULT,
Title nvarchar(60),
MedUrl nvarchar(75) NOT NULL,
MediaType nvarchar(30) NOT NULL,
CreatedDate date NOT NULL, 
CONSTRAINT check_CREATEDATE check (CreatedDate <= getdate())
)

CREATE TABLE tblCAT (
CatID int PRIMARY KEY,
CatName nvarchar(50) NOT NULL,
CatDesc nvarchar(150),
CatUrl nvarchar(75)
)
GO

CREATE TABLE tblPOST (
PostID int PRIMARY KEY,
PostTitle nvarchar(75) NOT NULL,
PostUrl nvarchar(75) NOT NULL,
PostExcerpt nvarchar(150),
PostContent nvarchar(600),
PublishedDate date,
CreatedDate date NOT NULL,
CONSTRAINT CHECK_CreatedDate check (CreatedDate < getdate()),
ModifiedDate date,
PostStatus nvarchar(15) NOT NULL,
PostAuthor int NOT NULL, 
CONSTRAINT FK_PostAuthor FOREIGN KEY (PostAuthor)
REFERENCES tblUSER(UserID),
PostEditor int,
CONSTRAINT FK_PostEditor FOREIGN KEY (PostEditor)
REFERENCES tblUSER(UserID),
FeatureImage int,
CONSTRAINT FK_PostFeature FOREIGN KEY (FeatureImage)
REFERENCES tblMEDIA(MedID)
)
GO

CREATE TABLE tblCOMMENT (
ComID int PRIMARY KEY,
PostID int NOT NULL,
CONSTRAINT FK_PostID FOREIGN KEY (PostID)
REFERENCES tblPOST(PostID),
ComAuthor int NOT NULL,
CONSTRAINT FK_ComAuthor FOREIGN KEY (ComAuthor)
REFERENCES tblUSER(UserID),
ComParent int,
CONSTRAINT FK_ComParent FOREIGN KEY (ComParent)
REFERENCES tblCOMMENT(ComID),
ComContent nvarchar(150),
CreatedDate date NOT NULL
)
GO

CREATE TABLE tblCATPOST (
PostID int NOT NULL,
CatID int NOT NULL,
CONSTRAINT PK_PostInCat PRIMARY KEY (PostID, CatID),
CONSTRAINT FK_PostInCat FOREIGN KEY (PostID)
REFERENCES tblPOST(PostID),
CONSTRAINT FK_CatHasPost FOREIGN KEY (CatID)
REFERENCES tblCAT(CatID),
PostCount int NOT NULL
)
GO